# Timing Constraints for PYNQ-Z2
# RISC-V + GPU Accelerator SoC

# Input clock - 125 MHz differential clock
# The Clock Wizard IP will handle the input clock constraint if configured correctly,
# but we can keep a simple one if needed. However, let's avoid overriding.

# Clock domain crossing constraints
# Using the default names generated by the Clock Wizard IP
set_clock_groups -asynchronous \
    -group [get_clocks -of_objects [get_pins clk_gen/inst/mmcm_adv_inst/CLKOUT0]] \
    -group [get_clocks -of_objects [get_pins clk_gen/inst/mmcm_adv_inst/CLKOUT1]]

# False paths
set_false_path -from [get_ports rst_n]
set_false_path -to [get_ports led*]

# BRAM constraints
set_max_delay -from [get_cells -hierarchical -filter {NAME =~ *frame_buffer*}] \
    -to [get_cells -hierarchical -filter {NAME =~ *vga*}] 10.0
