#!/bin/bash
# GitHub Push Helper Script

echo "=== GitHub Repository Setup ==="
echo ""
echo "The Git repository has been initialized and all files committed."
echo ""
echo "To push to GitHub, follow these steps:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: riscvgpuacc (or your preferred name)"
echo "   - Description: RISC-V + GPU Accelerator SoC for PYNQ-Z2"
echo "   - Make it Public or Private"
echo "   - DO NOT initialize with README, .gitignore, or license"
echo "   - Click 'Create repository'"
echo ""
echo "2. Copy the repository URL (HTTPS or SSH)"
echo ""
echo "3. Run these commands:"
echo "   git remote add origin <your-repo-url>"
echo "   git push -u origin main"
echo ""
echo "Example:"
echo "   git remote add origin https://github.com/yourusername/riscvgpuacc.git"
echo "   git push -u origin main"
echo ""
echo "Or with SSH:"
echo "   git remote add origin git@github.com:yourusername/riscvgpuacc.git"
echo "   git push -u origin main"
echo ""
